# Generated by Django 4.2.4 on 2023-10-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, verbose_name='categoria')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.actividad', verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profesor', models.IntegerField(verbose_name='id_profesor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('tel', models.IntegerField(verbose_name='Tel')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro', models.IntegerField(verbose_name='Nro')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='Administracion.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
