# Generated by Django 4.2.4 on 2023-10-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], default=1),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1),
        ),
    ]
