# Generated by Django 4.2.4 on 2023-10-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracion', '0001_initial'),
        ('Socios', '0002_socio_genero_alter_socio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripcion')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.actividad', verbose_name='Actividad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.categoria', verbose_name='Categoria')),
                ('nroSocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Socios.socio', verbose_name='Nro Socio')),
            ],
        ),
    ]
